apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "ReactApp"
  description: "create CaaS App"
  annotations:
    github.com/project-slug: JatinPanchal2/CaaSAPP87y78
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: "group:default/guests"
